name: Greetings

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for adding your first issue. We will be looking into it as soon as possible.'
        pr-message: 'Thank for your first PR. We really appreciate it!'
